image: jakzal/phpqa:php8

before_script:
    - composer install

cache:
    paths:
        - vendor/

stages:
    - SecurityChecker
    - CoodingStandards
    - UnitTests

security-checker:
    stage: SecurityChecker
    script:
        - security-checker security:check composer.composer.lock
    allow_failure: false

phpcs:
    stage: CoodingStandards
    script:
        - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./script:
    allow_failure: false

phpstan:
    stage: CoodingStandards
    script:
        - phpstan analyse ./script:
    allow_failure: false

twig-lint:
    stage: CoodingStandards
    script:
        - twig-lint lint ././templates
    allow_failure: false

phpunit:
    stage: UnitTests
    script: 
        - php bin/phpunit
    allow_failure: false


