version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '3306'
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
# phpMyAdmin container
  phpmyadmin:
# Use phpmyadmin/phpmyadmin:5.0.2 image
    image: 'phpmyadmin:latest'
# A name for the container
    #container_name: phpmyadmin_docker_clicrepare
# Restart if process is killed
    restart: always
# Connect to "my-network" network, as defined below
    #networks:
      #- dev
# Map port 8080 on the host to port 80 inside the container
# Syntax is: "HOST_PORT:CONTAINER_PORT"
    ports:
      - '8010:80'
# Pass a list of environment variables to the container
    environment:
      PMA_HOST: database
# Wait for "mysql" container to start first 
    depends_on:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
